### ISSUE TITLE
OS Agnostic

### ISSUE THREAD

**Issue by Javiertis** [Javiertis/AoC-Deno-Template#2]
Starting with PR #1 this issue will track the different features to make it work in an os agnostic way.

# TODO:

- [ ] start.ts day ranges should be 1-25
- [ ] A way to execute the different problems of each day
- [ ] Add a guide in the readme to run it.
